parameters:
#    civi_community_stats.example.class: Civi\CommunityStatsBundle\Example

services:
#    civi_community_stats.example:
#        class: %civi_community_stats.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
